---
version: 2
plan:
  project-key: ADGEXT
  key: BETESTSPECS
  name: browser extension - test
variables:
  dockerNode: adguard/extension-builder:18.19.0--0.1.3

stages:
  - Test:
      manual: 'false'
      final: 'false'
      jobs:
        - Test

Test:
  key: TEST
  other:
    clean-working-dir: true
  docker:
    image: ${bamboo.dockerNode}
    volumes:
      ${system.YARN_DIR}: "${bamboo.cacheYarn}"
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e
            ls -la

            # Fix mixed logs
            exec 2>&1

            # don't use --ignore-optional flag, because esbuild requires optional deps
            yarn install --silent --ignore-engines --ignore-platform --ignore-scripts

            yarn lint
            yarn test
            yarn dev

            yarn integration-test dev

            # Create artifacts directory if it doesn't exist
            mkdir -p artifacts

            # Copy all artifacts to the artifacts directory
            cp build/dev/build.txt artifacts/
            cp build/dev/chrome.zip artifacts/
            cp build/dev/chrome-mv3.zip artifacts/
            cp build/dev/edge.zip artifacts/
            cp build/dev/firefox-amo.zip artifacts/
            cp build/dev/firefox-standalone.zip artifacts/
            cp build/dev/opera.zip artifacts/
    - test-parser:
        type: junit
        test-results: '**/test-report.xml'
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -la

            echo "Size before cleanup:" && du -h | tail -n 1
            rm -rf node_modules build
            echo "Size after cleanup:" && du -h | tail -n 1
  artifacts:
    - name: build.txt
      location: artifacts
      pattern: build.txt
      required: true
    - name: chrome.zip
      location: artifacts
      pattern: chrome.zip
      required: true
    - name: chrome-mv3.zip
      location: artifacts
      pattern: chrome-mv3.zip
      required: true
    - name: edge.zip
      location: artifacts
      pattern: edge.zip
      required: true
    - name: firefox-amo.zip
      location: artifacts
      pattern: firefox-amo.zip
      required: true
    - name: firefox-standalone.zip
      location: artifacts
      pattern: firefox-standalone.zip
      required: true
    - name: opera.zip
      location: artifacts
      pattern: opera.zip
      required: true
  requirements:
    - adg-docker: 'true'

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: 'true'

notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
